repos:
-   repo: https://github.com/python/black
    rev: master
    hooks:
    - id: black
      language_version: python3
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black .
        language: system
        pass_filenames: false
