language: python
addons:
  apt:
    update: true
python:
 - "3.6"
install:
 - pip install .
 - apt-get install -y python-numpy python-dev cmake zlib1g-dev libjpeg-dev xvfb libav-tools xorg-dev python-opengl libboost-all-dev libsdl2-dev swig
 - pip install gym[all]
script:
 - python -m pytest test
