language: python
dist: bionic
python:
- 3.7
before_install:
- export POETRY_VERSION=1.1.8
- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
- poetry config virtualenvs.create false
install:
- poetry install
script:
- pytest
